// Do not edit this file. It is generated from the plugin config.
declare global {
  interface Window {
    wpReactPlugin: {
      baseUrl: string;
      root: string;
    };
  }
}

// wpParams is the object passed from PHP Plugin
const wpParams = window.wpReactPlugin || {};

// baseUrl is the path to the plugin folder. It is used to load assets from the plugin folder in the build.
export const baseUrl = wpParams.baseUrl || "";

// root is the DOM element where the app will be mounted
export const root = document.querySelector(wpParams.root || "#root");
